import React from "react";

export const Footer: React.FC = () => {
  return (
    <footer className="w-full border-t border-border bg-background py-8 px-6">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <span className="font-bold text-xl tracking-tighter text-foreground">AVKAST</span>
            <span className="text-[10px] px-1.5 py-0.5 rounded border border-primary/30 text-primary font-mono bg-primary/5">
              INSTITUTIONAL GRADE
            </span>
          </div>
          <p className="text-xs text-muted-foreground max-w-sm">
            Neo-Brokerage Asset Management for a transparent financial future.
            Built for 2026 Regulatory Environments.
          </p>
        </div>
        
        <div className="flex-1 max-w-2xl bg-muted/30 p-4 rounded-lg border border-border/50">
          <p className="text-[10px] leading-relaxed text-muted-foreground italic">
            <strong>Important Disclaimer:</strong> All predictions are generated by AI models and are for informational purposes only. 
            This is not financial advice. Past performance does not guarantee future results. 
            Regulatory compliance (EU AI Act) is maintained via immutable audit trails for every decision artifact.
          </p>
        </div>
        
        <div className="text-[10px] text-muted-foreground font-mono">
          © 2026 AVKAST INTELLIGENCE SV AB
        </div>
      </div>
    </footer>
  );
};
